export const CREATION_WORDS = "CREATION_WORDS";
export const ADD_WORD = "ADD_WORD";
export const CHANGE_MODAL = "CHANGE_MODAL";
export const CHANGE_AUTORISATION_MODAL = "CHANGE_AUTORISATION_MODAL";
export const DELETE_WORD = "DELETE_WORD";
export const DELETE_MODE = "DELETE_MODE";
export const PAGE_NUMBERS = "PAGE_NUMBERS";
export const PAGE_NUMBER = "PAGE_NUMBER";
export const PAGE_SLICES = "PAGE_SLICES";
export const SEARCH_FILTER = "SEARCH_FILTER";
export const NEW_WORDS_LIST = "NEW_WORDS_LIST";
export const CURRENT_ACCOUNT = "CURRENT_ACCOUNT";
export const AUTORIZATION = "AUTORIZATION";
export const REGISTRATION = "REGISTRATION";
export const CHANGE_REGISTRARION_MODAL = "CHANGE_REGISTRARION_MODAL";
export const UPDATE_DATA = "UPDATE_DATA";
export const PAGE_RESET = "PAGE_RESET";



